<?php
/**
 * Implementation of hook_menu().
 */
function civimobile_menu() {
    $items = array();
    
    // CiviMobile Homepage
	$items['civimobile'] = array(
      'title'            => 'CiviMobile',
      'description'      => 'A small but very effective mobile interface to your CiviCRM installation.',
      'page callback'    => '_civimobile_page',
	  'page arguments'   => array('home',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
    $items['civimobile/contact'] = array(
      'title'            => 'CiviMobile',
      'description'      => 'A small but very effective mobile interface to your CiviCRM installation.',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('contact_list',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
	$items['civimobile/contact/%'] = array(
      'title'            => 'Contact',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('contact',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
    $items['civimobile/contact/%/edit'] = array(
        'title'            => 'Contact',
        'page callback'    => '_civimobile_page',
        'page arguments'   => array('contact_edit',2),
        'access arguments' => array('access CiviCRM'),
        'type'             => MENU_NORMAL_ITEM,
      );
	$items['civimobile/structure'] = array(
      'title'            => 'Contact',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('pagestructure',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
	$items['civimobile/event'] = array(
      'title'            => 'Event',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('event_list',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
	$items['civimobile/event/%'] = array(
      'title'            => 'Event',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('event',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
	$items['civimobile/profile'] = array(
      'title'            => 'ProfileList',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('profile_list'),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
	$items['civimobile/profile/%'] = array(
      'title'            => 'Profile',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('profile'),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
	$items['civimobile/survey'] = array(
      'title'            => 'Case',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('survey_list',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
	$items['civimobile/survey/%/%'] = array(
      'title'            => 'Case',
      'page callback'    => '_civimobile_page', 
      'page arguments'   => array('survey_respondents',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );
  $items['civimobile/survey/%/%/%'] = array(
      'title'            => 'Case',
      'page callback'    => '_civimobile_page',
      'page arguments'   => array('survey',2),
      'access arguments' => array('access CiviCRM'),
      'type'             => MENU_NORMAL_ITEM,
    );  
  return $items;
}
function _civimobile_page($page,$param= null ) {
  civicrm_initialize();  
  //$civimobile_page_settings = _civimobile_vars_setup();
  $pagepath = drupal_get_path('module','civimobile')."/templates/civimobile.$page.tpl.php";
  include_once($pagepath);
  return NULL;
}